default: &default
  address:              smtp.gmail.com
  port:                 587
  domain:               yahoo.com
  user_name:            mica324@yahoo.com
  password:             Lantana2011
  authentication:       plain
  enable_starttls_auto: true

development:
  <<: *default

production:
  <<: *default